// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcdIhLvZGMcKG4otiUznaQ9Ld2ptpcEqA',
    appId: '1:992167857051:web:d0b2220bc0e74f965aaf3e',
    messagingSenderId: '992167857051',
    projectId: 'learning-managemet-syste-ab2c3',
    authDomain: 'learning-managemet-syste-ab2c3.firebaseapp.com',
    storageBucket: 'learning-managemet-syste-ab2c3.appspot.com',
    measurementId: 'G-RP0FG36B01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiVfa3p0G7-L_8zggohKbRKWCOXAVgEXQ',
    appId: '1:992167857051:android:b8647fa7c6b9b0cb5aaf3e',
    messagingSenderId: '992167857051',
    projectId: 'learning-managemet-syste-ab2c3',
    storageBucket: 'learning-managemet-syste-ab2c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdr3XGkiGHgtE-8AELCmkIFfEhIcs57vI',
    appId: '1:992167857051:ios:052c1146ee0f3ac65aaf3e',
    messagingSenderId: '992167857051',
    projectId: 'learning-managemet-syste-ab2c3',
    storageBucket: 'learning-managemet-syste-ab2c3.appspot.com',
    iosBundleId: 'com.example.learningManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdr3XGkiGHgtE-8AELCmkIFfEhIcs57vI',
    appId: '1:992167857051:ios:052c1146ee0f3ac65aaf3e',
    messagingSenderId: '992167857051',
    projectId: 'learning-managemet-syste-ab2c3',
    storageBucket: 'learning-managemet-syste-ab2c3.appspot.com',
    iosBundleId: 'com.example.learningManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcdIhLvZGMcKG4otiUznaQ9Ld2ptpcEqA',
    appId: '1:992167857051:web:bd998ba736cfcc515aaf3e',
    messagingSenderId: '992167857051',
    projectId: 'learning-managemet-syste-ab2c3',
    authDomain: 'learning-managemet-syste-ab2c3.firebaseapp.com',
    storageBucket: 'learning-managemet-syste-ab2c3.appspot.com',
    measurementId: 'G-YBFY84HMP3',
  );
}
